name: Deploy Storybooks

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3   # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build docs Storybooks
        run: | 
          npm install
          npm run storybook-web-docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: './docs/'
          name: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          # Upload entire repository
          artifact_name: 'docs'
          github-token: ${{ secrets.GITHUB_TOKEN }}