name: Deploy Storybooks

on:
  push:
    paths: ["storybook/**"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3   # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm install
      - run: npm run storybook-web-docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs